### ISSUE TITLE
Homepage UI loading issues on Chrome

### ISSUE THREAD

**Issue by pid1** [Lasagna-Love-Portal/project-ricotta#25]
On initial page load, the progress indicator, Create Account button, and Log In text renders in front of the photo gallery, then disappears. It does not re-appear until the photo gallery auto-scroll is triggered. The behavior is inconsistent, but seems to be more frequent when viewing on a narrow viewport.

**Environment**: Chrome 112.0.5615.137 on macOS Ventura 13.3.1 (M2)
**App Build**: Commit 81be0a27dc5ed46b77229cd6a457ac766ee35b94

I'm running the app via the new Dockerized environment in https://github.com/Lasagna-Love-Portal/project-ricotta/pull/24, which may have introduced the issue.

**Comment by pid1** [comment]
@allyson-s-code Wasn't sure if you saw this during your development. Any thoughts?

**Comment by pid1** [comment]
https://user-images.githubusercontent.com/4173362/235314843-ac3fd79c-d3e4-4f15-8346-826ccb9f19a8.mov

**Comment by allyson-s-code** [comment]
I'll take a look.  I did not notice that before but I definitely see it now.

**Comment by allyson-s-code** [comment]
It looks like giving the carousel a set height makes the load a lot better- the button is not loading up high and then jumping down.  It still seems a bit of a jumping load.  I'll see if I can get it smoother.

**Comment by mattkuznicki-ll** [comment]
Looks like https://github.com/Lasagna-Love-Portal/project-ricotta/pull/36 resolves this - thanks @allyson-s-code !
