### ISSUE TITLE
Docker container will run even when some TypeScript issues are present

### ISSUE THREAD

**Issue by mattkuznicki-ll** [Lasagna-Love-Portal/project-ricotta#33]
In testing https://github.com/Lasagna-Love-Portal/project-ricotta/pull/32 it was discovered that as of commit [4483304](https://github.com/Lasagna-Love-Portal/project-ricotta/pull/32/commits/4483304f4ac9cae610581d5c17b9bdb3963194a5) the project would run when run in a Docker container, but running `npx next build` would error out with TypeScript issues.

Best would be to prevent the Docker container from building if there are issues?
Or to recommend local compilation as a sanity check?
Or some other solution?

**Comment by pid1** [comment]
Deprecated as we are using nix builds
