### ISSUE TITLE
run-lint workflow natural language false positive

### ISSUE THREAD

**Issue by patmejia** [Lasagna-Love-Portal/project-ricotta#39]
### description: 
False positive in lint report: "github" used in link. i.e. https://github.com/Lasagna-Love-Portal/bechamel-api
Lint expected "GitHub" (PascalCase) 

### screenshot of workflow error:
<img width="348" alt="Screenshot 2023-05-20 at 9 48 54 AM" src="https://github.com/Lasagna-Love-Portal/project-ricotta/assets/92187562/e2c947b7-4ec4-4cb3-890d-5372d27025e5">

### zoomed screenshot of workflow error:
<img width="644" alt="Screenshot 2023-05-20 at 9 58 30 AM" src="https://github.com/Lasagna-Love-Portal/project-ricotta/assets/92187562/f1576470-de2f-4a55-9464-72f9fb18a760">

### raised error
```
/github/workspace/README.md
  89:31  ✓ error  Incorrect usage of the term: “Github”, use “GitHub” instead  terminology

✖ 1 problem (1 error, 0 warnings)
✓ 1 fixable problem.
Try to run: $ textlint --fix [file]
```

### fix? 

1. Open `README.md` file.
2. Find the line with the error (line 89).
3. Replace with fix, replace github with GitHub while potentially breaking link, avoid links with PascalCase?
4. Save the file.
5. Open a terminal or command prompt.
6. Navigate to the directory containing the file.
7. Run `textlint --fix README.md` command.
8. Verify the error is fixed in the file.
9. Commit and push the changes to the repository.

**Comment by patmejia** [comment]
Pending to try updating the README.md with the linting configurations mentioned in DEVELOPMENT.md. It's possible that the linter enforces global rules affecting the README.md update in question.

[DEVELOPMENT.md](https://github.com/Lasagna-Love-Portal/project-ricotta/blob/dev/DEVELOPMENT.md)

```
Running the linter locally
This repository uses github's Super Linter and we encourage running the linter against your changes before making a pull request to dev or main. You can run this locally using Docker:

Obtain the Super Linter Docker container: docker pull github/super-linter:latest
Invoke Docker to run the Super Linter against your project directory: docker run -e RUN_LOCAL=true -v [path-to-project]:/tmp/lint github/super-linter
Where [path-to-project] is the full path to your project.
```

**Comment by pid1** [comment]
Do we consider this a bug? The correct name of the product is indeed `GitHub` not `Github`, so I'd suggest the appropriate fix here is updating `README.md` with the Linter's suggestions.

**Comment by mattkuznicki-ll** [comment]
Issue believed resolved in https://github.com/Lasagna-Love-Portal/project-ricotta/pull/41.

**Comment by pid1** [comment]
Looks good, thanks!
