### ISSUE TITLE
Continue using next.js or discard and just use React?

### ISSUE THREAD

**Issue by mattkuznicki-ll** [Lasagna-Love-Portal/project-ricotta#43]
next.js is a framework that builds on React to move rendering of pages from client to server. next.js is intended for websites where data is not highly variable, where much can be pre-rendered on the server and updated on a periodic basis. next.js came into the project with the work to separate Project Ricotta out of its monorepo structure and into a Docker deployable container. It's not known whether this was an intentional decision, or one made for ease of getting that work done.

I propose the removal of next.js from the project and a shift back to using React on its own without next.js. This will shift page render predominantly back from the server to client-side rendering.

Pros:
* next.js can improve initial page rendering times for static content and for dynamic content where that content is not updated frequently.
* next.js improves SEO over just using React

Cons:
* Using next.js moves the project-ricotta repo away from our long-term goal of using the project-ricotta codebase as a starting point for Android & iOS apps via React Native. Some projects are out there for using next.js with React Native, though they appear to be fairly early efforts with significant issues.
* Many if not most of the pages on the volunteer portal are dynamic and content is driven from API calls that are not conducive to infrequent updates.
* Additional package maintenance and overhead that may not be giving any real return
* next.js 13 (the next upcoming version, currently in beta) is going to significantly restructure how projects are written, and will likely prompt significant effort if we want to move to it once out of beta

**Comment by funbunch** [comment]
It's my understanding the new recommendations for React are to use it with a full-stack framework, like Next or Remix. I haven't seen the new changes with Next 13 though.

**Comment by emmanolan** [comment]
@mattkuznicki-ll I think we should remove it, now is the best time to do it and if we find a need in the future, we can switch it back over

**Comment by mattkuznicki-ll** [comment]
In code & coffee call on June 6th, participants discussed and agreed that we will continue forward with using next.js 12 (the currently used next.js version), and not seek to move to a pure React project.
Part of the discussion surfaced that there are suitable ways to make pages that are not server-side rendered, which removes that objection. Additionally, next.js brings in significant developer tooling that it was pointed out we'll end up needing to find and bring in for a React project, so it does help with that.
